### ISSUE TITLE
preview strange (GNU emacs28 (master) and org master)

### ISSUE THREAD

**Issue by ouboub** [yangsheng6810/org-latex-impatient#10]
Hi
I am running Ubuntu 16.04 but upgraded 
npm 7.19.1
and 
node to 16.6.0
so I could install 
mathjax-node-cli

however when I use org-latex-impatient I see in the minibuffer a lot of log messages, but nothing you showed on your screenshots.
I attach a screenshot 
Uwe Brauer
![instant-rendering](https://user-images.githubusercontent.com/5957203/127614468-cb81c54a-ed54-4126-8e51-3c343b722ed9.png)

**Comment by yangsheng6810** [comment]
You might want to check if your Emacs is able to show an SVG file. If not, you might want to upgrade your Emacs. The latest release 27.2.

BTW, Ubuntu 16.04 is way way too old. As an LTS version, it reached its end of life this April. Please update do some more recent Ubuntu releases, or consider

**Comment by ouboub** [comment]
>>> "y" == yangsheng6810  ***@***.***> writes:

> You might want to check if your Emacs is able to show an SVG file. If not, you might want to upgrade your Emacs. The latest release 27.2.

Ah, this is a misundertanding, right? I said I have emacs28 installed and you want me too upgrade to 27.2?

However I found out that I can not open a svg file with my compiled options. I will file a backreport for this

> BTW, Ubuntu 16.04 is way way too old. As an LTS version, it reached
> its end of life this April. Please update do some more recent Ubuntu
> releases, or consider

Well I managed to upgrade node and npm to very recent version, so I don't think this is relevant here.

**Comment by yangsheng6810** [comment]
> Ah, this is a misundertanding, right? I said I have emacs28 installed and you want me too upgrade to 27.2?

Sorry, my fault. Somehow I miss the title of the issue and was wondering why you reported the version of npm and node, but not Emacs.

> However I found out that I can not open a svg file with my compiled options. I will file a backreport for this

There are quite a few compile flags that might be related. One thing to note is that Emacs 28 no longer needs `--with-imagemagick`. I believe to support SVG, it needs to be compiled with librsvg (no `--without-rsvg`). I am not an expert with the compile flags, but I believe a good starting point would be the compile flags of latest Debian or Ubuntu official packages.

**Comment by ouboub** [comment]
the point was I did not have the librsvg-2-dev
installed, only librsvg-2. In any case I recompiled by emacs and now I obtain the following behaviour:
![instantt](https://user-images.githubusercontent.com/5957203/127740925-59e8923d-9dd5-40dc-9c8c-1bd8e855ee21.png)

**Comment by ouboub** [comment]
if this is the exspected behaviour, I can close the issue

**Comment by yangsheng6810** [comment]
The picture you attached is too tiny for me to squint out, but seems the correct behavior.

**Comment by ouboub** [comment]
Here is a different screenshot, is the math expression supposed to be this tiny?
![instant2](https://user-images.githubusercontent.com/5957203/127746109-7735aa90-51d0-4c42-9d66-68083623d47b.png)

**Comment by yangsheng6810** [comment]
You can scale it by customizing `org-latex-impatient-scale`.

**Comment by ouboub** [comment]
I did this, changed it even to the value 8.0, but I don't notice any change

**Comment by yangsheng6810** [comment]
I checked Emacs master commit f6c5a801ef, with `emacs -q`, and scaling works fine for me. This might be related to the version of librsvg. Could you try also update your librsvg?

**Comment by ouboub** [comment]
upgradiing that library would require upgrade ubuntu, which I should do anyhow.
last try, you said you started emacs  -q,  (not -Q?)
what did you do next, just load your package

**Comment by ouboub** [comment]
I tried to start emacs -q or -Q and then loading your package, 
he told me I does not find s
which you require,
so please could you tell me what you did

**Comment by yangsheng6810** [comment]
Yes, I started with `emacs -q`, which I assume is the correct one. Not?

Here is the exact process I took:
1. Check out Emacs master commit f6c5a801ef
2. Compile with `git clean -fdx &&  ./autogen.sh && ./configure --with-modules --without-gconf --without-gsettings --with-json && make -j16`
3. Start emacs with `emacs -q`
4. Run the following to initialize `package.el`

**Comment by ouboub** [comment]
hm this works for me, so the problem is a strange settings of mine, sigh, I have to debug it

**Comment by ouboub** [comment]
Ok some strange setting in my custom file, now it works, thanks
