### ISSUE TITLE
`\usepackage` failed as undefined control sequence

### ISSUE THREAD

**Issue by minyez** [yangsheng6810/org-latex-impatient#11]
Hi,

Thanks for creating this package! The basic usage works perfectly for me. I went further to try to include the physics package, following readme, with the config
```emacs-lisp
(setq org-latex-impatient-user-latex-definitions
      '("\\usepackage{physics}"
        "\\newcommand{\\ensuremath}[1]{#1}"
        "\\renewcommand{\\usepackage}[2][]{}"))
```
but got TeX parse error: Undefined control sequence \usepackage. As indicated in readme, Mathjax does not support the usepackage command, so any way to include the raw `usepackage` would seem to fail. So I think that the related example in the readme is somewhat misleading.

**Comment by yangsheng6810** [comment]
Thanks for pointing it out. That part of readme is indeed misleading. It was added for a particular use case, which might be related to using a renderer other than MathJax. There is plan to support pdfLaTeX as renderer, which will support `\usepackage` but will run slower. I have updated the readme. Feel free to re-open this issue if you still find it misleading.
