### ISSUE TITLE
broken svg

### ISSUE THREAD

**Issue by deb75** [yangsheng6810/org-latex-impatient#12]
My configuration : 
- emacs master from a couple of weeks
- windows 11
- mingw64
- mathjax-node-cli just updated
- org-latex-impatient
```elisp
(use-package org-latex-impatient
  :defer t
  :hook (org-mode . org-latex-impatient-mode)
  :init
  (setq org-latex-impatient-tex2svg-bin "d:/xxx/Documents/utils/scoop/persist/nodejs/bin/tex2svg")
  :config
  (setq org-latex-impatient-delay 0.1
        org-latex-impatient-scale 1
        org-latex-impatient-posframe-position 'tex-end
        org-latex-impatient-border-width 1))

```
When I try to render simple formula ($a=b$), I get a very small box with apparently nothing drawn inside.

In the message buffer, each time I updated math formulas I get :  
```
﻿Invalid image size (see ‘max-image-size’)
Error parsing SVG image ‘(image :type svg :data <svg height="110%"><g transform="scale(1)"><svg xmlns:xlink="http://www.w3.org/1999/xlink" width="0" height="0.343ex" style="vertical-align: -0.171ex;" viewBox="0 -73.8 0 147.5" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg" aria-labelledby="MathJax-SVG-1-Title">
<title id="MathJax-SVG-1-Title"></title>
<defs aria-hidden="true"></defs>
<g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)" aria-hidden="true"></g>
</svg>
</g></svg> :scale 1 :max-width 2941 :max-height 1813 :format nil :transform-smoothing t)’
```

However, I checked that `tex2svg` works fine :
```
tex2svg "\frac{x}{y}$ > test.svg
```

I can see the svg in emacs.

What is wrong ?

**Comment by deb75** [comment]
Any hints ?

**Comment by yangsheng6810** [comment]
I do not use Emacs on Windows, so I am not sure what could be the main reason. But the error message does look familiar to me. Could you check the version of librsvg, and/or try Emacs 28.1 (released recently)? Might be related to [bug 44206](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=44206).

**Comment by deb75** [comment]
Hello,

Thanks for your answer.

Here is the `librsvg` version :  
```
mingw64/mingw-w64-x86_64-librsvg 2.52.6-1
```

I use `emacs-master` (29.X I think) compiled a couple of weeks ago.

**Comment by deb75** [comment]
Here is the svg file in attachment, generated with
```
tex2svg "\int_0^1\frac{x}{y}" > test.svg
```
![test](https://user-images.githubusercontent.com/19540378/162700609-02d91b0d-240f-45c2-8069-7d431e0fc8a4.svg)

Here is the content : 
```xml
<svg xmlns:xlink="http://www.w3.org/1999/xlink" width="6.071ex" height="6.176ex" style="vertical-align: -2.338ex;" viewBox="0 -1652.5 2614 2659.1" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg" aria-labelledby="MathJax-SVG-1-Title">
<title id="MathJax-SVG-1-Title">integral Subscript 0 Superscript 1 Baseline StartFraction x Over y EndFraction</title>
<defs aria-hidden="true">
<path stroke-width="1" id="E1-MJSZ2-222B" d="M114 -798Q132 -824 165 -824H167Q195 -824 223 -764T275 -600T320 -391T362 -164Q365 -143 367 -133Q439 292 523 655T645 1127Q651 1145 655 1157T672 1201T699 1257T733 1306T777 1346T828 1360Q884 1360 912 1325T944 1245Q944 1220 932 1205T909 1186T887 1183Q866 1183 849 1198T832 1239Q832 1287 885 1296L882 1300Q879 1303 874 1307T866 1313Q851 1323 833 1323Q819 1323 807 1311T775 1255T736 1139T689 936T633 628Q574 293 510 -5T410 -437T355 -629Q278 -862 165 -862Q125 -862 92 -831T55 -746Q55 -711 74 -698T112 -685Q133 -685 150 -700T167 -741Q167 -789 114 -798Z"></path>
<path stroke-width="1" id="E1-MJMAIN-31" d="M213 578L200 573Q186 568 160 563T102 556H83V602H102Q149 604 189 617T245 641T273 663Q275 666 285 666Q294 666 302 660V361L303 61Q310 54 315 52T339 48T401 46H427V0H416Q395 3 257 3Q121 3 100 0H88V46H114Q136 46 152 46T177 47T193 50T201 52T207 57T213 61V578Z"></path>
<path stroke-width="1" id="E1-MJMAIN-30" d="M96 585Q152 666 249 666Q297 666 345 640T423 548Q460 465 460 320Q460 165 417 83Q397 41 362 16T301 -15T250 -22Q224 -22 198 -16T137 16T82 83Q39 165 39 320Q39 494 96 585ZM321 597Q291 629 250 629Q208 629 178 597Q153 571 145 525T137 333Q137 175 145 125T181 46Q209 16 250 16Q290 16 318 46Q347 76 354 130T362 333Q362 478 354 524T321 597Z"></path>
<path stroke-width="1" id="E1-MJMATHI-78" d="M52 289Q59 331 106 386T222 442Q257 442 286 424T329 379Q371 442 430 442Q467 442 494 420T522 361Q522 332 508 314T481 292T458 288Q439 288 427 299T415 328Q415 374 465 391Q454 404 425 404Q412 404 406 402Q368 386 350 336Q290 115 290 78Q290 50 306 38T341 26Q378 26 414 59T463 140Q466 150 469 151T485 153H489Q504 153 504 145Q504 144 502 134Q486 77 440 33T333 -11Q263 -11 227 52Q186 -10 133 -10H127Q78 -10 57 16T35 71Q35 103 54 123T99 143Q142 143 142 101Q142 81 130 66T107 46T94 41L91 40Q91 39 97 36T113 29T132 26Q168 26 194 71Q203 87 217 139T245 247T261 313Q266 340 266 352Q266 380 251 392T217 404Q177 404 142 372T93 290Q91 281 88 280T72 278H58Q52 284 52 289Z"></path>
<path stroke-width="1" id="E1-MJMATHI-79" d="M21 287Q21 301 36 335T84 406T158 442Q199 442 224 419T250 355Q248 336 247 334Q247 331 231 288T198 191T182 105Q182 62 196 45T238 27Q261 27 281 38T312 61T339 94Q339 95 344 114T358 173T377 247Q415 397 419 404Q432 431 462 431Q475 431 483 424T494 412T496 403Q496 390 447 193T391 -23Q363 -106 294 -155T156 -205Q111 -205 77 -183T43 -117Q43 -95 50 -80T69 -58T89 -48T106 -45Q150 -45 150 -87Q150 -107 138 -122T115 -142T102 -147L99 -148Q101 -153 118 -160T152 -167H160Q177 -167 186 -165Q219 -156 247 -127T290 -65T313 -9T321 21L315 17Q309 13 296 6T270 -6Q250 -11 231 -11Q185 -11 150 11T104 82Q103 89 103 113Q103 170 138 262T173 379Q173 380 173 381Q173 390 173 393T169 400T158 404H154Q131 404 112 385T82 344T65 302T57 280Q55 278 41 278H27Q21 284 21 287Z"></path>
</defs>
<g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)" aria-hidden="true">
 <use xlink:href="#E1-MJSZ2-222B" x="0" y="0"></use>
 <use transform="scale(0.707)" xlink:href="#E1-MJMAIN-31" x="1500" y="1540"></use>
 <use transform="scale(0.707)" xlink:href="#E1-MJMAIN-30" x="787" y="-1270"></use>
<g transform="translate(1514,0)">
<g transform="translate(286,0)">
<rect stroke="none" width="692" height="60" x="0" y="220"></rect>
 <use xlink:href="#E1-MJMATHI-78" x="60" y="676"></use>
 <use xlink:href="#E1-MJMATHI-79" x="97" y="-686"></use>
</g>
</g>
</g>
</svg>

```

I can also open the svg file in emacs without any errors.

I tried `org-latex-impatient` on another screen and equations are still not rendered, I only get a small empty box ot the size of a character. However, I do no more have the previous error with emacs. I think the previous error is due to the fact that my default screen is hidpi and that I use a zooming effect on it (in windows 11, about 250%).

However, even without this error, equations are not displayed.

Regards

**Comment by deb75** [comment]
Igoogled the error, but without much success, any hints ?

There are something strange with the error : it complains as if the image size exceeds the `max-image-size`
but in the svg itself I read `width="0"` ??

Regards

**Comment by yangsheng6810** [comment]
You mean you can open the SVG file with Emacs directly, but still see "Invalid image size" errors with `org-latex-impatient`? Or Emacs just refuses to show the SVG file?

**Comment by deb75** [comment]
I can open svg files manually generated by `text2svg` within emacs. No errors.

Errors only occur within `org-latex-impatient`. Is it possible to save the svg image generated by `org-latex-impatient` into a file ? so that I can try to open it by hand.

You can see in the working file above that there is `width="6.071ex"` whereas in the failing svg I have `width="0"`. Isn't it part of the issue ?

Regards

**Comment by yangsheng6810** [comment]
You can add the following to function `org-latex-impatient--fill-posframe-buffer`, right before its call to `org-latex-impatient--insert-into-posframe-buffer`
```emacs-lisp
(with-temp-file (make-temp-file "org-latex-impatient-" nil ".svg")
   (insert ss))
```
The svg will be saved to "/tmp/org-latex-impatient-*.svg", and you can check that. The svg generated by `org-latex-impatient` is a wrapped version of the one returned by `tex2svg`, so that scaling can be handled. If you do not need scaling, you can remove the wrapper part (check the definition of function `org-latex-impatient--fill-posframe-buffer`).

**Comment by deb75** [comment]
Here is an example of such temporary file : 
```xml
<svg height="110%"><g transform="scale(0.01)"><svg xmlns:xlink="http://www.w3.org/1999/xlink" width="0" height="0.343ex" style="vertical-align: -0.171ex;" viewBox="0 -73.8 0 147.5" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg" aria-labelledby="MathJax-SVG-1-Title">
<title id="MathJax-SVG-1-Title"></title>
<defs aria-hidden="true"></defs>
<g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)" aria-hidden="true"></g>
</svg>
</g></svg>
```

This is supposed to represent : 
```latex
    \begin{equation}
    \label{eq:1}
    \frac{1}{2}\int_{0}^{1}
    \end{equation}
```

But svg file does not seem to contain anything and in fact, whatever I write in the latex environment does not change the svg file content.

So there seems to have an issue regarding how `org-latex-impatient` retrieves the latex fragments.

Is it possible to see what input `org-latex-impatient` gives to `tex2svg` ?

Regards

**Comment by yangsheng6810** [comment]
In `org-latex-impatient--render`, put `(message "org-latex-impatient-tex-string is: %S" tex-string)` after `(get-buffer-create org-latex-impatient--output-buffer)`

**Comment by deb75** [comment]
Thanks,

Here is the string corresponding to previous latex environment : 
```
"\\newcommand{\\ensuremath}[1]{#1}
\\renewcommand{\\usepackage}[2][]{}
\\color{#839496}{    \\begin{equation}
    \\label{eq:1}
    \\frac{1}{2}\\int_{0}^{1}
    \\end{equation}
}" 
```

Then, I manully invoked `text2svg` : 
```
tex2svg previous-string > 1.svg
```

and emacs correctly loads the resulting svg
![1](https://user-images.githubusercontent.com/19540378/163278976-37319e36-fb4e-4f40-85ea-f815d312ad75.svg)

which looks more correct : 
```xml
<svg xmlns:xlink="http://www.w3.org/1999/xlink" width="5.904ex" height="6.176ex" style="vertical-align: -2.338ex;" viewBox="0 -1652.5 2542 2659.1" role="img" focusable="false" xmlns="http://www.w3.org/2000/svg" aria-labelledby="MathJax-SVG-1-Title">
<title id="MathJax-SVG-1-Title">one-half integral Subscript 0 Superscript 1 Baseline</title>
<defs aria-hidden="true">
<path stroke-width="1" id="E1-MJMAIN-31" d="M213 578L200 573Q186 568 160 563T102 556H83V602H102Q149 604 189 617T245 641T273 663Q275 666 285 666Q294 666 302 660V361L303 61Q310 54 315 52T339 48T401 46H427V0H416Q395 3 257 3Q121 3 100 0H88V46H114Q136 46 152 46T177 47T193 50T201 52T207 57T213 61V578Z"></path>
<path stroke-width="1" id="E1-MJMAIN-32" d="M109 429Q82 429 66 447T50 491Q50 562 103 614T235 666Q326 666 387 610T449 465Q449 422 429 383T381 315T301 241Q265 210 201 149L142 93L218 92Q375 92 385 97Q392 99 409 186V189H449V186Q448 183 436 95T421 3V0H50V19V31Q50 38 56 46T86 81Q115 113 136 137Q145 147 170 174T204 211T233 244T261 278T284 308T305 340T320 369T333 401T340 431T343 464Q343 527 309 573T212 619Q179 619 154 602T119 569T109 550Q109 549 114 549Q132 549 151 535T170 489Q170 464 154 447T109 429Z"></path>
<path stroke-width="1" id="E1-MJSZ2-222B" d="M114 -798Q132 -824 165 -824H167Q195 -824 223 -764T275 -600T320 -391T362 -164Q365 -143 367 -133Q439 292 523 655T645 1127Q651 1145 655 1157T672 1201T699 1257T733 1306T777 1346T828 1360Q884 1360 912 1325T944 1245Q944 1220 932 1205T909 1186T887 1183Q866 1183 849 1198T832 1239Q832 1287 885 1296L882 1300Q879 1303 874 1307T866 1313Q851 1323 833 1323Q819 1323 807 1311T775 1255T736 1139T689 936T633 628Q574 293 510 -5T410 -437T355 -629Q278 -862 165 -862Q125 -862 92 -831T55 -746Q55 -711 74 -698T112 -685Q133 -685 150 -700T167 -741Q167 -789 114 -798Z"></path>
<path stroke-width="1" id="E1-MJMAIN-30" d="M96 585Q152 666 249 666Q297 666 345 640T423 548Q460 465 460 320Q460 165 417 83Q397 41 362 16T301 -15T250 -22Q224 -22 198 -16T137 16T82 83Q39 165 39 320Q39 494 96 585ZM321 597Q291 629 250 629Q208 629 178 597Q153 571 145 525T137 333Q137 175 145 125T181 46Q209 16 250 16Q290 16 318 46Q347 76 354 130T362 333Q362 478 354 524T321 597Z"></path>
</defs>
<g stroke="currentColor" fill="currentColor" stroke-width="0" transform="matrix(1 0 0 -1 0 0)" aria-hidden="true">
<g fill="#839496" stroke="#839496">
<g fill="#839496" stroke="#839496">
<g fill="#839496" stroke="#839496">
<g transform="translate(120,0)">
<rect stroke="none" width="620" height="60" x="0" y="220"></rect>
<g fill="#839496" stroke="#839496" transform="translate(60,676)">
 <use xlink:href="#E1-MJMAIN-31"></use>
</g>
<g fill="#839496" stroke="#839496" transform="translate(60,-687)">
 <use xlink:href="#E1-MJMAIN-32"></use>
</g>
</g>
</g>
<g fill="#839496" stroke="#839496" transform="translate(1027,0)">
<g fill="#839496" stroke="#839496">
 <use xlink:href="#E1-MJSZ2-222B"></use>
</g>
<g fill="#839496" stroke="#839496" transform="translate(1060,1089)">
<g fill="#839496" stroke="#839496">
<g fill="#839496" stroke="#839496">
 <use transform="scale(0.707)" xlink:href="#E1-MJMAIN-31"></use>
</g>
</g>
</g>
<g fill="#839496" stroke="#839496" transform="translate(556,-898)">
<g fill="#839496" stroke="#839496">
<g fill="#839496" stroke="#839496">
 <use transform="scale(0.707)" xlink:href="#E1-MJMAIN-30"></use>
</g>
</g>
</g>
</g>
</g>
</g>
</g>
</svg>
```

There seems to be an issue with the process itself.

Regards

**Comment by deb75** [comment]
Hi,

I found the issue which is the way `make-process` calls `tex2svg`.

The default is to call a bash script wrapper which does not work natively on windows 11.

I had to hardcode the executable path like this : 
```elisp
        (make-process
         :name "org-latex-impatient"
         :buffer org-latex-impatient--output-buffer
         :command (append (list "c:/path/to/node.exe"
                                "c:/path/to/mathjax-node-cli/tex2svg" ;; not the bash script wrapper, but the javascript node
                                tex-string)
                          (when org-latex-impatient--is-inline
                            '("--inline")))
```
and then, it works.

It should also certainly work with linux. Perhaps could you retrieve this in order to make something more robust and portable.

Regards

**Comment by yangsheng6810** [comment]
Congratulations on making it work!

Thanks for your suggestion. However, I do not really understand what you mean. For me on Linux, the file `~/node_modules/mathjax-node-cli/bin/tex2svg` is itself an executable **node js** script, as its first line says: `#! /usr/bin/env node`, which asks to be executed by node js. This is not a **bash** wrapper. I am not familiar with how things work on Windows 11, would it work if you add the directory of node.exe to your PATH? Note you need to make sure PATH is also correctly set inside Emacs. I assume this will look up the location of node.exe automatically. It sounds a bit weird to me to hard code the location of nodejs, as it is supposed to be looked up automatically. 

I noticed the binary location in your original post was "d:/xxx/Documents/utils/scoop/persist/nodejs/bin/tex2svg", and in your latest post "c:/path/to/mathjax-node-cli/tex2svg". The latter looks more familiar to me, though still misses a directory level `bin` comparing to my location. Is there something related here?

Another request, I am not a Windows user, at least I do not use Emacs on Windows. Could you please write a section in FAQ to help future users set up on Windows?

**Comment by deb75** [comment]
Hi,

Thanks for your reply.

I think `make-process` needs an executable file in the first element of the command list. Then, `make-process` gives this executable to the OS which returns a running process.

On linux, you can give any script as an executable because the OS linux is able to find the correct interpreter by itself (the true executable). On windows, unless being under WSL, it does not work : windows cannot understand the "shebang" at beginning of script and even if it could, "/usr/bin/env bash" or "/bin/sh" are not valid paths under windows.

However, I am a bit confused because if you look at `math-preview`'s implementation, you may see :  
```elisp
(start-process "math-preview" nil math-preview-command))
```

where `math-preview-command` refers to this script :  
```bash
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/node_modules/math-preview/math-preview.js" "$@"
else
  exec node  "$basedir/node_modules/math-preview/math-preview.js" "$@"
fi
```

which is exactly the same as the one I wanted to use for `tex2svg` and, the point is that it works perfectly
well with `math-preview`, but not with `tex2svg`.

If you can explain why it works in one case, but not with the other, I am interested.

Regards
