### ISSUE TITLE
Show preview in right below current cursor

### ISSUE THREAD

**Issue by liebkne** [yangsheng6810/org-latex-impatient#5]
Thanks for the great package! It would be nice to have an option show preview right below current cursor.

**Comment by yangsheng6810** [comment]
Could you check if the branch [posframe-at-point](https://github.com/yangsheng6810/org-latex-impatient/tree/posframe-at-point) solves the problem? You can show the preview right below current cursor with `(setq org-latex-impatient-posframe-position 'point)`. Note after a preview is generated, it will NOT move with your cursor unless the underlying TeX string has changed.

**Comment by liebkne** [comment]
Unfortunately, it didn't work. The preview still being displayed in the end point of the segment. The content in the second buffer in the screenshot shows my setup.

<img width="832" alt="Screen Shot 2020-12-11 at 8 08 18 AM" src="https://user-images.githubusercontent.com/5475262/101844898-6a4db280-3b88-11eb-8b45-c7f031dcd4bf.png">

**Comment by yangsheng6810** [comment]
I see what you are asking for. This behavior is by design: inline math is displayed around cursor, while display math is displayed in the center. Please refer to [documentation](https://github.com/yangsheng6810/org-latex-impatient#customization) for details. If you want to show everything around the cursor, try the following:
`(setq org-latex-impatient-posframe-position-handler #'posframe-poshandler-point-bottom-left-corner)`

**Comment by liebkne** [comment]
Thanks for the details. Setting `(setq org-latex-impatient-posframe-position-handler #'posframe-poshandler-point-bottom-left-corner)` results in the following screenshot. I'd like to display the preview in the red box location.

**Comment by yangsheng6810** [comment]
I cannot see a screenshot

**Comment by liebkne** [comment]
Sorry, I've updated my last comment.

**Comment by yangsheng6810** [comment]
You would need both settings to achieve that.

**Comment by liebkne** [comment]
The followings with the `posframe-at-point` solves the issue

```
(setq org-latex-impatient-posframe-position 'point
         org-latex-impatient-posframe-position-handler #'posframe-poshandler-point-bottom-left-corner)
```

**Comment by yangsheng6810** [comment]
The comment (997dd3f41a00df21cf85f90d26731bb9879a871e) has been merged into `develop`, and the branch `posframe-at-point` has been deleted.
