### ISSUE TITLE
[Question] How to hide border of the preview?

### ISSUE THREAD

**Issue by liebkne** [yangsheng6810/org-latex-impatient#7]
Is there a way to hide the border of the preview? Thanks.
<img width="433" alt="Screen Shot 2020-12-10 at 10 07 50 PM" src="https://user-images.githubusercontent.com/5475262/101783834-b28fb500-3b35-11eb-98cd-958e87fc0d81.png">

**Comment by yangsheng6810** [comment]
`(setq org-latex-impatient-border-width 1)`

**Comment by liebkne** [comment]
I think you mean `(setq org-latex-impatient-border-width 0)`. Setting it to `0` solved my issue. Thank you!
