### ISSUE TITLE
can't display the preview

### ISSUE THREAD

**Issue by jerasky** [yangsheng6810/org-latex-impatient#9]
the error message is:  "tex parse error: undefined control sequence \justifying" below the latex's code in org file buffer

**Comment by yangsheng6810** [comment]
Please provide a minimum org file you are using. As far as I know, `\justifying` is not a standard TeX/LaTeX command.

**Comment by jerasky** [comment]
in my org file have two preambles:
 #+LATEX_HEADER: \justifying
#+LATEX_HEADER: \let\raggedright\justifying

**Comment by yangsheng6810** [comment]
This package is built on MathJax, and will **not** work for most if not all additional packages (There is plan for using LaTeX, but still in construction). You can customize `org-latex-impatient-user-latex-definitions` to override the offending macros, like how `\usepackage` is handled. Such customization will only affect the preview by this package, and nothing else.

**Comment by jerasky** [comment]
but when I make a org file has nothing besides a "$y$" , then, a bundle of text messages show below, as this:
![image](https://user-images.githubusercontent.com/5634688/113399342-a4aabc00-93d2-11eb-89a2-e94160f77a69.png)

**Comment by yangsheng6810** [comment]
Please check if your Emacs can open an SVG file as an image. It is known that some build of Emacs does not support this (e.g. some Emacs build on Mac OSX).
